### ISSUE TITLE
Demo notebook is misleading

### ISSUE THREAD

**Issue by psychemedia** [jtpio/jupyterlite-demo#1]
The demo notebook is misleading - when I tried running the demo locally at least, there is a lot of whitespace at the top of the notebook that makes it look like the page is blank (and broken....)

![image](https://user-images.githubusercontent.com/82988/121498604-7a7a0980-c9d4-11eb-9c48-d83875ae1a07.png)

Are the line breaks in the notebook for a reason?

![image](https://user-images.githubusercontent.com/82988/121498514-646c4900-c9d4-11eb-8cb1-54f5cbe672db.png)

**Comment by jtpio** [comment]
> Are the line breaks in the notebook for a reason?

They were added for presentation purposes, to leave some space between the cells when going through the notebook over a video call.

Happy to remove them, or at least the top one.

**Comment by jtpio** [comment]
> Happy to remove them, or at least the top one.

Done in https://github.com/jtpio/jupyterlite-demo/commit/8635bf35c52b4a592fa49a58061bd8f1a3bf4437, visible live on the new deployment: https://jtpio.github.io/jupyterlite-demo/retro/notebooks/?path=2021-06-03-pydata-paris.ipynb
